[platformio]
default_envs = usb

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino, espidf
monitor_speed = 115200
; XIAO ESP32C6 has 4MB Flash. custom.csv includes OTA and Zigbee NVRAM partitions with larger app size
board_build.partitions = custom.csv
lib_deps =
    olikraus/U8g2@^2.34.22
extra_scripts = pre:generate_certs.py
build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D ZIGBEE_MODE_NCP
    -I components/esp-zigbee-ncp/include

[env:usb]
upload_protocol = esptool

[env:ota]
upload_protocol = espota
upload_port = esp32c6-z2m-ncp.local ; IP address or mDNS hostname
upload_flags =
    --auth=admin
