#ifndef ZB_COORDINATOR_CTX_H
#define ZB_COORDINATOR_CTX_H 1

#include "zb_ncp.h"

#define COORDINATOR_ENDPOINT 1

#define ZB_COORDINATOR_DEVICE_ID 0xbeef
#define ZB_COORDINATOR_GP_DEVICE_ID 0x0061

#define ZB_COORDINATOR_IN_CLUSTER_NUM 7
#define ZB_COORDINATOR_OUT_CLUSTER_NUM 22
#define ZB_COORDINATOR_CLUSTER_NUM (ZB_COORDINATOR_IN_CLUSTER_NUM + ZB_COORDINATOR_OUT_CLUSTER_NUM)

#define ZB_COORDINATOR_GP_IN_CLUSTER_NUM 0
#define ZB_COORDINATOR_GP_OUT_CLUSTER_NUM 1
#define ZB_COORDINATOR_GP_CLUSTER_NUM (ZB_COORDINATOR_GP_IN_CLUSTER_NUM + ZB_COORDINATOR_GP_OUT_CLUSTER_NUM)

#define ZB_DECLARE_COORDINATOR_CLUSTER_LIST(cluster_list_name, basic_attr_list, identify_attr_list, groups_attr_list, scenes_attr_list, on_off_attr_list, time_attr_list, ota_client_attr_list, color_control_attr_list) \
zb_zcl_cluster_desc_t cluster_list_name[] = { \
    /* IN_CLUSTERS (Server Role) - 7 */ \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_BASIC, ZB_ZCL_ARRAY_SIZE(basic_attr_list, zb_zcl_attr_t), basic_attr_list, ZB_ZCL_CLUSTER_SERVER_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_IDENTIFY, ZB_ZCL_ARRAY_SIZE(identify_attr_list, zb_zcl_attr_t), identify_attr_list, ZB_ZCL_CLUSTER_SERVER_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_ON_OFF, ZB_ZCL_ARRAY_SIZE(on_off_attr_list, zb_zcl_attr_t), on_off_attr_list, ZB_ZCL_CLUSTER_SERVER_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_TIME, ZB_ZCL_ARRAY_SIZE(time_attr_list, zb_zcl_attr_t), time_attr_list, ZB_ZCL_CLUSTER_SERVER_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    { ZB_ZCL_CLUSTER_ID_OTA_UPGRADE, 0, NULL, ZB_ZCL_CLUSTER_SERVER_ROLE, ZB_ZCL_MANUF_CODE_INVALID, NULL }, \
    { 0x001aU, 0, NULL, ZB_ZCL_CLUSTER_SERVER_ROLE, ZB_ZCL_MANUF_CODE_INVALID, NULL }, \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_COLOR_CONTROL, ZB_ZCL_ARRAY_SIZE(color_control_attr_list, zb_zcl_attr_t), color_control_attr_list, ZB_ZCL_CLUSTER_SERVER_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    /* OUT_CLUSTERS (Client Role) - 22 */ \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_BASIC, ZB_ZCL_ARRAY_SIZE(basic_attr_list, zb_zcl_attr_t), basic_attr_list, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_IDENTIFY, ZB_ZCL_ARRAY_SIZE(identify_attr_list, zb_zcl_attr_t), identify_attr_list, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_GROUPS, ZB_ZCL_ARRAY_SIZE(groups_attr_list, zb_zcl_attr_t), groups_attr_list, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_SCENES, ZB_ZCL_ARRAY_SIZE(scenes_attr_list, zb_zcl_attr_t), scenes_attr_list, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_ON_OFF, ZB_ZCL_ARRAY_SIZE(on_off_attr_list, zb_zcl_attr_t), on_off_attr_list, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_LEVEL_CONTROL, 0, NULL, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_TIME, ZB_ZCL_ARRAY_SIZE(time_attr_list, zb_zcl_attr_t), time_attr_list, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_OTA_UPGRADE, ZB_ZCL_ARRAY_SIZE(ota_client_attr_list, zb_zcl_attr_t), ota_client_attr_list, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_POLL_CONTROL, 0, NULL, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_COLOR_CONTROL, ZB_ZCL_ARRAY_SIZE(color_control_attr_list, zb_zcl_attr_t), color_control_attr_list, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_ILLUMINANCE_MEASUREMENT, 0, NULL, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_TEMP_MEASUREMENT, 0, NULL, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_REL_HUMIDITY_MEASUREMENT, 0, NULL, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_OCCUPANCY_SENSING, 0, NULL, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_IAS_ZONE, 0, NULL, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_METER_IDENTIFICATION, 0, NULL, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    { 0x0b03U, 0, NULL, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID, NULL }, \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_ELECTRICAL_MEASUREMENT, 0, NULL, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_METERING, 0, NULL, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID), \
    { ZB_ZCL_CLUSTER_ID_TOUCHLINK_COMMISSIONING, 0, NULL, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID, NULL }, \
    { ZB_ZCL_CLUSTER_ID_IR_BLASTER, 0, NULL, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID, NULL }, \
    { 0xfc02U, 0, NULL, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID, NULL } \
}

#define ZB_DECLARE_COORDINATOR_GP_CLUSTER_LIST(cluster_list_name) \
zb_zcl_cluster_desc_t cluster_list_name[] = { \
    ZB_ZCL_CLUSTER_DESC(ZB_ZCL_CLUSTER_ID_GREEN_POWER, 0, NULL, ZB_ZCL_CLUSTER_CLIENT_ROLE, ZB_ZCL_MANUF_CODE_INVALID) \
}

#define ZB_ZCL_DECLARE_COORDINATOR_SIMPLE_DESC(ep_name, ep_id, in_clust_num, out_clust_num) \
    ZB_DECLARE_SIMPLE_DESC(in_clust_num, out_clust_num); \
    ZB_AF_SIMPLE_DESC_TYPE(in_clust_num, out_clust_num) simple_desc_##ep_name = { \
        ep_id, ZB_AF_HA_PROFILE_ID, ZB_COORDINATOR_DEVICE_ID, zb_ncp::DEVICE_VERSION, 0, \
        in_clust_num, out_clust_num, { \
            ZB_ZCL_CLUSTER_ID_BASIC, ZB_ZCL_CLUSTER_ID_IDENTIFY, ZB_ZCL_CLUSTER_ID_ON_OFF, ZB_ZCL_CLUSTER_ID_TIME, ZB_ZCL_CLUSTER_ID_OTA_UPGRADE, 0x001aU, ZB_ZCL_CLUSTER_ID_COLOR_CONTROL, \
            ZB_ZCL_CLUSTER_ID_BASIC, ZB_ZCL_CLUSTER_ID_IDENTIFY, ZB_ZCL_CLUSTER_ID_GROUPS, ZB_ZCL_CLUSTER_ID_SCENES, ZB_ZCL_CLUSTER_ID_ON_OFF, ZB_ZCL_CLUSTER_ID_LEVEL_CONTROL, ZB_ZCL_CLUSTER_ID_TIME, ZB_ZCL_CLUSTER_ID_OTA_UPGRADE, ZB_ZCL_CLUSTER_ID_POLL_CONTROL, ZB_ZCL_CLUSTER_ID_COLOR_CONTROL, ZB_ZCL_CLUSTER_ID_ILLUMINANCE_MEASUREMENT, ZB_ZCL_CLUSTER_ID_TEMP_MEASUREMENT, ZB_ZCL_CLUSTER_ID_REL_HUMIDITY_MEASUREMENT, ZB_ZCL_CLUSTER_ID_OCCUPANCY_SENSING, ZB_ZCL_CLUSTER_ID_IAS_ZONE, ZB_ZCL_CLUSTER_ID_METER_IDENTIFICATION, 0x0b03U, ZB_ZCL_CLUSTER_ID_ELECTRICAL_MEASUREMENT, ZB_ZCL_CLUSTER_ID_METERING, ZB_ZCL_CLUSTER_ID_TOUCHLINK_COMMISSIONING, ZB_ZCL_CLUSTER_ID_IR_BLASTER, 0xfc02U \
        } \
    }

#define ZB_ZCL_DECLARE_COORDINATOR_GP_SIMPLE_DESC(ep_name, ep_id, in_clust_num, out_clust_num) \
    ZB_DECLARE_SIMPLE_DESC(in_clust_num, out_clust_num); \
    ZB_AF_SIMPLE_DESC_TYPE(in_clust_num, out_clust_num) simple_desc_##ep_name = { \
        ep_id, ZB_AF_GP_PROFILE_ID, ZB_COORDINATOR_GP_DEVICE_ID, zb_ncp::DEVICE_VERSION, 0, \
        in_clust_num, out_clust_num, { ZB_ZCL_CLUSTER_ID_GREEN_POWER } \
    }

#define ZB_DECLARE_COORDINATOR_EP(ep_name, ep_id, cluster_list) \
    ZB_ZCL_DECLARE_COORDINATOR_SIMPLE_DESC(ep_name, ep_id, ZB_COORDINATOR_IN_CLUSTER_NUM, ZB_COORDINATOR_OUT_CLUSTER_NUM); \
    ZB_AF_DECLARE_ENDPOINT_DESC(ep_name, ep_id, ZB_AF_HA_PROFILE_ID, 0, NULL, \
        ZB_ZCL_ARRAY_SIZE(cluster_list, zb_zcl_cluster_desc_t), cluster_list, \
        (zb_af_simple_desc_1_1_t*)&simple_desc_##ep_name, 0, NULL, 0, NULL)

#define ZB_DECLARE_COORDINATOR_GP_EP(ep_name, ep_id, cluster_list) \
    ZB_ZCL_DECLARE_COORDINATOR_GP_SIMPLE_DESC(ep_name, ep_id, ZB_COORDINATOR_GP_IN_CLUSTER_NUM, ZB_COORDINATOR_GP_OUT_CLUSTER_NUM); \
    ZB_AF_DECLARE_ENDPOINT_DESC(ep_name, ep_id, ZB_AF_GP_PROFILE_ID, 0, NULL, \
        ZB_ZCL_ARRAY_SIZE(cluster_list, zb_zcl_cluster_desc_t), cluster_list, \
        (zb_af_simple_desc_1_1_t*)&simple_desc_##ep_name, 0, NULL, 0, NULL)

#endif /* ZB_COORDINATOR_CTX_H */
